name: Scrape Cineco latest data

on:
  workflow_dispatch:
  schedule:
    # At 4:16 UTC-5
    - cron: '16 9 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      BUCKET: ${{ secrets.BUCKET }}
      AWS_ROLE: ${{ secrets.AWS_ROLE_NAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.lock'
      - run: pip install -c pyproject.lock .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - run: scrape-cineco
        env:
          AWS_PROFILE: default
